from __future__ import annotations

"""Exact Base atomic-call simulator.

The simulator is deliberately fail-closed. It only reports PASS when a deployed
DragonAtomicExecutor can execute the complete Aave flash-loan callback path via
eth_call on the current Base state. Before an executor address is configured it
returns a non-passing result; it never upgrades a quote into an execution proof.
"""

from dataclasses import dataclass
from decimal import Decimal
import os


@dataclass(frozen=True)
class AtomicSimulationResult:
    passed: bool
    block_number: int
    target: str
    gas_estimate: int
    reason: str
    execution_simulation: bool = True


class BaseAtomicSimulator:
    def __init__(self, *, min_profit: Decimal = Decimal("0.005")):
        self.min_profit = Decimal(min_profit)
        if self.min_profit < Decimal("0.005"):
            raise ValueError("minimum profit floor cannot be below 0.005")

    def simulate(self, *, adapter, opportunity, first_execution, second_execution) -> AtomicSimulationResult:
        if int(opportunity.chain_id) != 8453:
            return AtomicSimulationResult(False, 0, "", 0, "Base simulator only")

        executor = os.getenv("DRAGON_ATOMIC_EXECUTOR", "").strip()
        if not executor:
            return AtomicSimulationResult(False, 0, "", 0, "DRAGON_ATOMIC_EXECUTOR not configured")

        w3 = getattr(adapter, "w3", None)
        if w3 is None:
            evm = getattr(adapter, "evm", None)
            w3 = getattr(evm, "w3", None) if evm is not None else None
        if w3 is None:
            return AtomicSimulationResult(False, 0, executor, 0, "no Base Web3 provider")

        try:
            executor = w3.to_checksum_address(executor)
            asset = w3.to_checksum_address(opportunity.quote_token)
            first_target = w3.to_checksum_address(first_execution.target)
            second_target = w3.to_checksum_address(second_execution.target)

            # The executor ABI is intentionally local and minimal. The actual
            # router calldata is generated by Dragon's verified DEX adapter.
            abi = [{
                "inputs": [
                    {"internalType": "address", "name": "asset", "type": "address"},
                    {"internalType": "uint256", "name": "amount", "type": "uint256"},
                    {"components": [
                        {"internalType": "address", "name": "target", "type": "address"},
                        {"internalType": "address", "name": "tokenIn", "type": "address"},
                        {"internalType": "address", "name": "tokenOut", "type": "address"},
                        {"internalType": "uint256", "name": "amountIn", "type": "uint256"},
                        {"internalType": "uint256", "name": "minAmountOut", "type": "uint256"},
                        {"internalType": "bytes", "name": "data", "type": "bytes"},
                    ], "internalType": "struct DragonAtomicExecutor.Leg", "name": "first", "type": "tuple"},
                    {"components": [
                        {"internalType": "address", "name": "target", "type": "address"},
                        {"internalType": "address", "name": "tokenIn", "type": "address"},
                        {"internalType": "address", "name": "tokenOut", "type": "address"},
                        {"internalType": "uint256", "name": "amountIn", "type": "uint256"},
                        {"internalType": "uint256", "name": "minAmountOut", "type": "uint256"},
                        {"internalType": "bytes", "name": "data", "type": "bytes"},
                    ], "internalType": "struct DragonAtomicExecutor.Leg", "name": "second", "type": "tuple"},
                ],
                "name": "startFlashLoan",
                "outputs": [],
                "stateMutability": "nonpayable",
                "type": "function",
            }]
            contract = w3.eth.contract(address=executor, abi=abi)
            first = (
                first_target,
                w3.to_checksum_address(first_execution.token_in),
                w3.to_checksum_address(first_execution.token_out),
                int(first_execution.amount_in),
                int(first_execution.amount_out),
                first_execution.data,
            )
            second = (
                second_target,
                w3.to_checksum_address(second_execution.token_in),
                w3.to_checksum_address(second_execution.token_out),
                int(second_execution.amount_in),
                int(second_execution.amount_out),
                second_execution.data,
            )
            tx = contract.functions.startFlashLoan(
                asset, int(opportunity.quote_amount), first, second
            ).build_transaction({"from": executor})

            block = int(w3.eth.block_number)
            gas = int(w3.eth.estimate_gas(tx))
            # eth_call is the decisive check. It executes the full transaction
            # against the current state without broadcasting it.
            w3.eth.call(tx)
            return AtomicSimulationResult(True, block, executor, gas, "atomic flash-loan path eth_call passed")
        except Exception as exc:
            return AtomicSimulationResult(
                False,
                int(getattr(w3.eth, "block_number", 0)),
                executor,
                0,
                f"atomic eth_call failed: {type(exc).__name__}",
            )
