"""Responsive live dashboard for the Dragon arbitrage engine."""

HTML = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#090b10"><title>Dragon | Live Control Room</title>
<style>
:root{--bg:#090b10;--panel:#11151d;--panel2:#151a23;--line:#252c38;--text:#f4f6f8;--muted:#8d98a8;--gold:#c9a85b;--green:#42d392;--red:#ff5f6d;--amber:#f2bd58;--blue:#62a8ff}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% -10%,#20283a 0,#090b10 42%);color:var(--text);font:14px Inter,system-ui,-apple-system,Segoe UI,sans-serif}main{max-width:1280px;margin:auto;padding:18px}.top{display:flex;align-items:center;justify-content:space-between;gap:14px;margin-bottom:18px}.brand{display:flex;align-items:center;gap:12px}.logo{width:46px;height:46px;border:1px solid #4a3e25;border-radius:14px;display:grid;place-items:center;color:var(--gold);font-size:25px;background:#0d1016}.title h1{margin:0;font-size:22px}.title p{margin:3px 0 0;color:var(--muted);font-size:12px}.live{border:1px solid #385d49;background:#0f1d17;color:var(--green);padding:8px 12px;border-radius:999px;font-weight:700}.live.off{border-color:#61343a;background:#1b1013;color:var(--red)}.hero{display:grid;grid-template-columns:1.6fr 1fr;gap:12px}.panel{background:linear-gradient(145deg,var(--panel),#0e1218);border:1px solid var(--line);border-radius:16px;padding:16px;box-shadow:0 10px 30px #0004}.statusgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.status{background:var(--panel2);border:1px solid var(--line);border-radius:12px;padding:12px}.status b{display:block;font-size:13px}.status span{display:block;color:var(--muted);font-size:11px;margin-top:4px}.dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:7px;background:var(--red)}.ok .dot{background:var(--green);box-shadow:0 0 10px #42d392}.warn .dot{background:var(--amber)}.pnl{font-size:34px;font-weight:800;margin:6px 0}.gold{color:var(--gold)}.muted{color:var(--muted)}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-top:12px}.metric{background:var(--panel);border:1px solid var(--line);border-radius:13px;padding:13px}.metric .label{color:var(--muted);font-size:11px;text-transform:uppercase;letter-spacing:.08em}.metric .num{font-size:24px;font-weight:800;margin-top:5px}.section{margin-top:12px}.sectionhead{display:flex;justify-content:space-between;align-items:center;margin-bottom:9px}.sectionhead h2{font-size:14px;margin:0}.badge{padding:4px 8px;border-radius:7px;background:#1a202a;color:var(--muted);font-size:10px}.diagnostics{display:grid;grid-template-columns:1fr 1fr;gap:12px}.bar{height:9px;background:#202630;border-radius:99px;overflow:hidden;margin:6px 0 10px}.fill{height:100%;width:0;background:var(--gold);border-radius:99px}.diagrow{display:grid;grid-template-columns:150px 1fr 55px;align-items:center;gap:8px;font-size:11px}.events{max-height:360px;overflow:auto}.event{display:grid;grid-template-columns:76px 110px 1fr;gap:8px;padding:9px 0;border-bottom:1px solid #202630;font-size:11px}.event .kind{font-weight:800}.event .msg{color:#c5ccd6}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.footer{margin-top:12px;color:var(--muted);font-size:10px;text-align:center}
@media(max-width:850px){.hero,.diagnostics{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.statusgrid{grid-template-columns:1fr}.top{align-items:flex-start}.event{grid-template-columns:65px 85px 1fr}}
</style></head><body><main>
<div class="top"><div class="brand"><div class="logo">🐉</div><div class="title"><h1>Dragon Live Control Room</h1><p>Binance Spot triangular arbitrage • real-time execution monitor</p></div></div><div id="mode" class="live">● CONNECTING</div></div>
<div class="hero"><section class="panel"><div class="sectionhead"><h2>Execution status</h2><span id="age" class="badge">updating</span></div><div class="statusgrid"><div id="ws" class="status"><b><i class="dot"></i>Market WebSocket</b><span>Binance depth feed</span></div><div id="api" class="status"><b><i class="dot"></i>Binance API</b><span>Authenticated account access</span></div><div id="engine" class="status"><b><i class="dot"></i>Engine</b><span>Scanner and executor</span></div></div><div class="section"><div class="muted">Realized P&amp;L</div><div id="pnl" class="pnl">0.000000 USDT</div><div class="muted">Available USDT <b id="bal">0</b> • Dynamic taker fee <b id="fee">0.00 bps</b></div></div></section>
<section class="panel"><div class="sectionhead"><h2>Risk &amp; execution</h2><span class="badge">LIVE GATES</span></div><div class="diagrow"><span>Net edge threshold</span><span class="mono" id="edge">7.00 bps</span><span></span></div><div class="diagrow"><span>Risk budget</span><span class="mono" id="risk">calculated</span><span></span></div><div class="diagrow"><span>Execution latency</span><span class="mono" id="lat">0 ms</span><span></span></div><div class="diagrow"><span>Circuit trips</span><span class="mono" id="circuit">0</span><span></span></div><div class="diagrow"><span>Balance refreshes</span><span class="mono" id="refresh">0</span><span></span></div></section></div>
<div class="metrics"><div class="metric"><div class="label">Triangles</div><div class="num" id="tri">0</div></div><div class="metric"><div class="label">Symbols</div><div class="num" id="sym">0</div></div><div class="metric"><div class="label">Streams</div><div class="num" id="streams">0</div></div><div class="metric"><div class="label">Depth updates</div><div class="num" id="depth">0</div></div><div class="metric"><div class="label">Scans</div><div class="num" id="scans">0</div></div><div class="metric"><div class="label">Opportunities</div><div class="num" id="opp">0</div></div><div class="metric"><div class="label">Executions</div><div class="num" id="exec">0</div></div><div class="metric"><div class="label">Filled cycles</div><div class="num" id="filled">0</div></div></div>
<div class="section diagnostics"><section class="panel"><div class="sectionhead"><h2>Why trades are / aren't happening</h2><span id="rejtotal" class="badge">0 decisions</span></div><div id="bars"></div></section><section class="panel"><div class="sectionhead"><h2>System health</h2><span class="badge">LIVE</span></div><div class="diagrow"><span>Execution errors</span><b id="errors">0</b><span></span></div><div class="diagrow"><span>Risk blocks</span><b id="blocks">0</b><span></span></div><div class="diagrow"><span>Reconnects</span><b id="reconnects">0</b><span></span></div><div class="diagrow"><span>Subscription ACKs</span><b id="acks">0</b><span></span></div><div class="diagrow"><span>Last opportunity</span><span id="lastopp">none</span><span></span></div><div class="diagrow"><span>Last execution</span><span id="lastexec">none</span><span></span></div></section></div>
<section class="panel section"><div class="sectionhead"><h2>Live event stream</h2><span class="badge">auto refresh 2s</span></div><div id="events" class="events"><div class="muted">Waiting for engine events...</div></div></section>
<div class="footer">Dragon dashboard • telemetry is observational and does not bypass Binance execution, filter, fee, slippage, stale-data, or risk controls.</div>
</main><script>
let prev=null,lastPoll=Date.now();const $=id=>document.getElementById(id);const fmt=n=>Number(n||0).toLocaleString(undefined,{maximumFractionDigits:3});const time=t=>t?new Date(Number(t)*1000).toLocaleTimeString():"none";
function setStatus(id,ok,label){const e=$(id);e.className='status '+(ok?'ok':'');e.querySelector('b').innerHTML='<i class="dot"></i>'+label}
function render(s){
 setStatus('ws',!!s.ws_connected,'Market WebSocket');setStatus('api',!!s.binance_authenticated,'Binance API');setStatus('engine',s.status==='running','Engine');
 const live=!!s.live&&!s.dry_run;$('mode').textContent=live?'● LIVE EXECUTION':'● SAFE / PAPER';$('mode').className='live '+(live?'':'off');
 $('pnl').textContent=Number(s.realized_pnl_usdt||0).toFixed(6)+' USDT';$('pnl').className='pnl '+(Number(s.realized_pnl_usdt||0)>=0?'gold':'');$('bal').textContent=s.free_usdt||'0';$('fee').textContent=Number(s.dynamic_fee_bps||0).toFixed(2)+' bps';
 [['tri','triangles'],['sym','symbols'],['streams','market_streams'],['depth','depth_updates'],['scans','scans'],['opp','opportunities'],['exec','executions'],['filled','ledger_filled'],['errors','execution_errors'],['blocks','risk_blocks'],['reconnects','reconnects'],['acks','subscription_acks'],['circuit','circuit_breaker_trips'],['refresh','balance_refreshes']].forEach(([a,b])=>$(a).textContent=fmt(s[b]));
 $('edge').textContent=''+(s.min_net_edge_bps??'7')+' bps';$('lat').textContent=(s.last_execution_latency_ms??0)+' ms';const r=s.free_usdt?Number(s.free_usdt)*0.01:0;$('risk').textContent=Math.min(25,r).toFixed(4)+' USDT';$('lastopp').textContent=time(s.last_opportunity);$('lastexec').textContent=time(s.last_execution);
 const rej=s.rejection||{},total=Number(s.rejection_total||0);$('rejtotal').textContent=fmt(total)+' decisions';const keys=['NO_LIQUIDITY','STALE','FEE_REJECTED','SLIPPAGE_REJECTED','NET_EDGE_REJECTED','NET_EDGE_PASSED'];const max=Math.max(1,...keys.map(k=>Number(rej[k]||0)));$('bars').innerHTML=keys.map(k=>{let v=Number(rej[k]||0);return '<div class="diagrow"><span>'+k.replaceAll('_',' ')+'</span><div class="bar"><div class="fill" style="width:'+((v/max)*100).toFixed(1)+'%"></div></div><span>'+fmt(v)+'</span></div>'}).join('');
 const ev=(s.recent||[]).slice().reverse();$('events').innerHTML=ev.length?ev.map(e=>'<div class="event"><span class="muted">'+time(e.ts)+'</span><span class="kind">'+(e.kind||'EVENT')+'</span><span class="msg">'+String(e.message||'')+(e.path?' <span class="mono">['+e.path.join(' → ')+']</span>':'')+(e.net_bps!=null?' <b>'+Number(e.net_bps).toFixed(3)+' bps</b>':'')+'</span></div>').join(''):'<div class="muted">Waiting for engine events...</div>';
 $('age').textContent='updated '+new Date().toLocaleTimeString();lastPoll=Date.now();
}
async function tick(){try{const j=await (await fetch('/health?ts='+Date.now(),{cache:'no-store'})).json();render(j.state||{});prev=j.state||{}}catch(e){$('mode').textContent='● DASHBOARD ERROR';$('mode').className='live off'}}tick();setInterval(tick,2000);
</script></body></html>'''
